"""Build a water trimer geometry from internal parameters and return a pyscf.gto.Mole.

Function: build_water_trimer(params)

Parameters expected in `params` (dict keys):
- r_o1o2, r_o2o3: distances between oxygens (Angstrom)
- angle_o1o2o3: angle at O2 (degrees) between O1-O2-O3

For each water molecule i in [1,2,3], keys:
- r_oh_i: O-H bond length (Angstrom)
- angle_hoh_i: H-O-H angle (degrees)
- theta_i: in-plane rotation around z-axis (degrees)
- phi_i: out-of-plane tilt around local y' axis (degrees)

Returns a pyscf.gto.Mole object with 3 O and 6 H atoms.
"""

import numpy as np
import os
try:
	from pyscf import gto
except Exception:
	# Allow import error at module import time; raise later when user tries to build mol
	gto = None


def _Rz(deg):
	t = np.deg2rad(deg)
	c = np.cos(t)
	s = np.sin(t)
	return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _Ry(deg):
	t = np.deg2rad(deg)
	c = np.cos(t)
	s = np.sin(t)
	return np.array([[c, 0.0, s], [0.0, 1.0, 0.0], [-s, 0.0, c]])


def build_water_trimer(params, basis='sto-3g'):
	"""Build a pyscf.gto.Mole for a water trimer from internal parameters.

	params: dict with keys described in module docstring. Missing per-molecule keys
			will use common defaults for typical water geometry.

	Returns: pyscf.gto.Mole
	"""
	if gto is None:
		raise ImportError('pyscf is required to build the molecule. Install pyscf to proceed.')

	# Required O-O parameters
	r_o1o2 = float(params.get('r_o1o2', 2.8))
	r_o2o3 = float(params.get('r_o2o3', 2.8))
	angle_o1o2o3 = float(params.get('angle_o1o2o3', 60.0))  # degrees

	# Place O2 at origin, O1 on +x axis, O3 by r, angle at O2
	O2 = np.array([0.0, 0.0, 0.0])
	O1 = np.array([r_o1o2, 0.0, 0.0])
	theta = np.deg2rad(angle_o1o2o3)
	O3 = np.array([r_o2o3 * np.cos(theta), r_o2o3 * np.sin(theta), 0.0])
	oxy_coords = [O1, O2, O3]

	atoms = []

	# helper default geometry for water
	default_r_oh = 0.9584  # Å
	default_angle_hoh = 104.45  # degrees

	for i, Ocoord in enumerate(oxy_coords, start=1):
		# per-molecule parameters
		r_oh = float(params.get(f'r_oh_{i}', params.get('r_oh', default_r_oh)))
		angle_hoh = float(params.get(f'angle_hoh_{i}', params.get('angle_hoh', default_angle_hoh)))
		theta_i = float(params.get(f'theta_{i}', params.get('theta', 0.0)))
		phi_i = float(params.get(f'phi_{i}', params.get('phi', 0.0)))

		# place oxygen
		atoms.append(('O', tuple(Ocoord.tolist())))

		# Build H positions in local frame where O is at origin, molecular plane is xy-plane,
		# and bisector of H-O-H is along +x axis
		a = np.deg2rad(angle_hoh / 2.0)
		x = r_oh * np.cos(a)
		y = r_oh * np.sin(a)
		H1_local = np.array([x, y, 0.0])
		H2_local = np.array([x, -y, 0.0])

		# Build combined rotation: first rotate in-plane by theta_i about z, then tilt by phi_i about local y'.
		# As shown in notes, net rotation applied to local vectors is R = Rz(theta_i) @ Ry(phi_i)
		R = _Rz(theta_i) @ _Ry(phi_i)

		H1_rot = R.dot(H1_local) + Ocoord
		H2_rot = R.dot(H2_local) + Ocoord

		atoms.append(('H', tuple(H1_rot.tolist())))
		atoms.append(('H', tuple(H2_rot.tolist())))

	# Build PySCF molecule
	mol = gto.M()
	# atoms format: list of (symbol, (x,y,z)) pairs
	mol.atom = atoms
	mol.unit = 'Angstrom'
	mol.basis = basis
	mol.verbose = 0
	mol.build()

	return mol


if __name__ == '__main__':
	# Example parameter set for demonstration
	params = {
		'r_o1o2': 2.8,
		'r_o2o3': 2.8,
		'angle_o1o2o3': 60.0,
		# molecule 1
		'r_oh_1': 0.9584,
		'angle_hoh_1': 104.45,
		'theta_1': 10.0,
		'phi_1': 20.0,
		# molecule 2
		'r_oh_2': 0.9584,
		'angle_hoh_2': 104.45,
		'theta_2': 130.0,
		'phi_2': -15.0,
		# molecule 3
		'r_oh_3': 0.9584,
		'angle_hoh_3': 104.45,
		'theta_3': -80.0,
		'phi_3': 5.0,
	}

	try:
		mol = build_water_trimer(params)
		coords = mol.atom_coords()
		symbols = [a[0] for a in mol._atom]
		print('Generated coordinates (symbol, x, y, z) in Angstrom:')
		for sym, c in zip(symbols, coords):
			print(f"{sym:2s}  {c[0]:10.6f}  {c[1]:10.6f}  {c[2]:10.6f}")
		# Save geometry to an XYZ file in the same directory as this script (the 'moje' folder)
		try:
			script_dir = os.path.dirname(os.path.abspath(__file__))
			xyz_path = os.path.join(script_dir, 'water_trimer.xyz')
			with open(xyz_path, 'w') as f:
				f.write(f"{len(symbols)}\n")
				f.write('Generated by build_water_trimer\n')
				for sym, c in zip(symbols, coords):
					f.write(f"{sym} {c[0]:.8f} {c[1]:.8f} {c[2]:.8f}\n")
			print(f"Wrote geometry to {xyz_path}")
		except Exception as e:
			print('Error writing XYZ file:', e)
	except Exception as e:
		print('Error building or printing molecule:', e)

