#!/usr/bin/env python3
"""Main workflow: build water trimer from internal coords, run PySCF, save XYZ, and visualize.

Usage: run as a script. Requires pyscf, numpy and matplotlib.
"""
import os
import sys
import numpy as np

try:
    from pyscf import gto, scf
except Exception as e:
    gto = scf = None


def _Rz(deg):
    t = np.deg2rad(deg)
    c = np.cos(t)
    s = np.sin(t)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _Ry(deg):
    t = np.deg2rad(deg)
    c = np.cos(t)
    s = np.sin(t)
    return np.array([[c, 0.0, s], [0.0, 1.0, 0.0], [-s, 0.0, c]])


def build_water_trimer(params):
    """Create a pyscf.gto.Mole-like object with atom positions set but do not call build().

    Returns an instance of pyscf.gto.M with `atom` and `unit` set. Caller should set
    `mol.basis` and call `mol.build()` before running PySCF drivers.
    """
    if gto is None:
        raise ImportError('pyscf is required to build the molecule.')

    # O-O backbone
    r_o1o2 = float(params.get('r_o1o2', 2.8))
    r_o2o3 = float(params.get('r_o2o3', 2.8))
    angle_o1o2o3 = float(params.get('angle_o1o2o3', 60.0))

    O2 = np.array([0.0, 0.0, 0.0])
    O1 = np.array([r_o1o2, 0.0, 0.0])
    theta = np.deg2rad(angle_o1o2o3)
    O3 = np.array([r_o2o3 * np.cos(theta), r_o2o3 * np.sin(theta), 0.0])
    oxy_coords = [O1, O2, O3]

    atoms = []

    default_r_oh = 0.9584
    default_angle_hoh = 104.45

    for i, Ocoord in enumerate(oxy_coords, start=1):
        r_oh = float(params.get(f'r_oh_{i}', params.get('r_oh', default_r_oh)))
        angle_hoh = float(params.get(f'angle_hoh_{i}', params.get('angle_hoh', default_angle_hoh)))
        theta_i = float(params.get(f'theta_{i}', params.get('theta', 0.0)))
        phi_i = float(params.get(f'phi_{i}', params.get('phi', 0.0)))

        atoms.append(('O', tuple(Ocoord.tolist())))

        a = np.deg2rad(angle_hoh / 2.0)
        x = r_oh * np.cos(a)
        y = r_oh * np.sin(a)
        H1_local = np.array([x, y, 0.0])
        H2_local = np.array([x, -y, 0.0])

        R = _Rz(theta_i) @ _Ry(phi_i)
        H1_rot = R.dot(H1_local) + Ocoord
        H2_rot = R.dot(H2_local) + Ocoord

        atoms.append(('H', tuple(H1_rot.tolist())))
        atoms.append(('H', tuple(H2_rot.tolist())))

    mol = gto.M()
    mol.atom = atoms
    mol.unit = 'Angstrom'
    return mol


def save_to_xyz(mol, filename):
    """Write molecule geometry to an XYZ file. Accepts a pyscf.gto.Mole (built or not)."""
    # Try to get symbols and coordinates
    try:
        coords = mol.atom_coords()
        symbols = [a[0] for a in mol._atom]
    except Exception:
        # use mol.atom attribute (list of (symbol, (x,y,z)))
        atom_list = getattr(mol, 'atom', None)
        if atom_list is None:
            raise ValueError('Molecule has no atom information')
        symbols = [a[0] for a in atom_list]
        coords = np.array([a[1] for a in atom_list], dtype=float)

    with open(filename, 'w') as f:
        f.write(f"{len(symbols)}\n")
        f.write('Generated by run_water_trimer_workflow\n')
        for sym, c in zip(symbols, coords):
            f.write(f"{sym} {c[0]:.8f} {c[1]:.8f} {c[2]:.8f}\n")


def visualize_from_xyz(filename):
    """Read an XYZ file and display a 3D plot with atoms and bonds (only O-H).

    This uses matplotlib; it will call plt.show() at the end.
    """
    try:
        import matplotlib.pyplot as plt
        from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
    except Exception:
        raise ImportError('matplotlib is required for visualization')

    # parse xyz
    with open(filename, 'r') as f:
        lines = [l.strip() for l in f if l.strip()]
    atom_lines = lines[2:]
    symbols = []
    coords = []
    for ln in atom_lines:
        parts = ln.split()
        symbols.append(parts[0])
        coords.append([float(parts[1]), float(parts[2]), float(parts[3])])
    coords = np.array(coords)

    X = coords[:, 0]
    Y = coords[:, 1]
    Z = coords[:, 2]

    fig = plt.figure(figsize=(8, 6))
    ax = fig.add_subplot(111, projection='3d')

    idx_O = [i for i, s in enumerate(symbols) if s.upper().startswith('O')]
    idx_H = [i for i, s in enumerate(symbols) if s.upper().startswith('H')]

    # Assign each H to nearest O
    assigned = {o_idx: [] for o_idx in idx_O}
    O_coords = coords[idx_O]
    for h_idx in idx_H:
        h_coord = coords[h_idx]
        dists = np.linalg.norm(O_coords - h_coord, axis=1)
        oi = int(np.argmin(dists))
        o_idx = idx_O[oi]
        assigned[o_idx].append(h_idx)

    # Draw O-H bonds
    for o_idx, h_list in assigned.items():
        O_coord = coords[o_idx]
        # keep up to two closest if more assigned
        if len(h_list) > 2:
            h_list = sorted(h_list, key=lambda hi: np.linalg.norm(coords[hi] - O_coord))[:2]
        for h_idx in h_list:
            hx, hy, hz = coords[h_idx]
            ox, oy, oz = O_coord
            ax.plot([ox, hx], [oy, hy], [oz, hz], color='lightgray', linewidth=1.0, zorder=1)

    # NOTE: Do not draw O-O backbone lines here — keep only O-H bonds in the visualization.

    # Draw atom markers on top
    if len(idx_O) > 0:
        ax.scatter(X[idx_O], Y[idx_O], Z[idx_O], c='red', s=220, edgecolors='k', label='O', zorder=10)
    if len(idx_H) > 0:
        ax.scatter(X[idx_H], Y[idx_H], Z[idx_H], c='lightgray', s=60, edgecolors='k', label='H', zorder=10)

    ax.set_xlabel('X Coordinate')
    ax.set_ylabel('Y Coordinate')
    ax.set_zlabel('Z Coordinate')
    ax.set_title('Water Trimer 3D Structure')

    # equal aspect
    try:
        ax.set_box_aspect([1, 1, 1])
    except Exception:
        max_range = np.array([X.max()-X.min(), Y.max()-Y.min(), Z.max()-Z.min()]).max()
        xmid = 0.5 * (X.max() + X.min())
        ymid = 0.5 * (Y.max() + Y.min())
        zmid = 0.5 * (Z.max() + Z.min())
        ax.set_xlim(xmid - max_range/2, xmid + max_range/2)
        ax.set_ylim(ymid - max_range/2, ymid + max_range/2)
        ax.set_zlim(zmid - max_range/2, zmid + max_range/2)

    ax.legend()
    plt.tight_layout()
    plt.show()


def main():
    if gto is None or scf is None:
        print('pyscf is required to run this workflow. Please install pyscf.', file=sys.stderr)
        sys.exit(1)

    # Step 1: parameters
    params = {
        'r_o1o2': 2.8,
        'r_o2o3': 2.8,
        'angle_o1o2o3': 60.0,
        # molecule 1
        'r_oh_1': 0.9584,
        'angle_hoh_1': 104.45,
        'theta_1': 10.0,
        'phi_1': 20.0,
        # molecule 2
        'r_oh_2': 0.9584,
        'angle_hoh_2': 104.45,
        'theta_2': 130.0,
        'phi_2': -15.0,
        # molecule 3
        'r_oh_3': 0.9584,
        'angle_hoh_3': 104.45,
        'theta_3': -80.0,
        'phi_3': 5.0,
    }

    # Step 2: build molecule (do not call mol.build() yet)
    mol = build_water_trimer(params)
    mol.basis = 'sto-3g'
    mol.build()

    # Step 3: save geometry
    xyz_file = os.path.join(os.getcwd(), 'water_trimer.xyz')
    save_to_xyz(mol, xyz_file)
    print(f'Wrote geometry to: {xyz_file}')

    # Step 4: run PySCF SCF (RHF)
    myhf = scf.RHF(mol)
    energy = myhf.kernel()
    print(f'Final SCF energy: {energy}')

    # Step 5: analysis
    try:
        myhf.analyze()
    except Exception as e:
        print('Warning: analyze() failed:', e)

    # Step 6: visualize
    visualize_from_xyz(xyz_file)


if __name__ == '__main__':
    main()
